import { v4 as uuidv4 } from 'uuid';
import { Recipe, Favorite } from './app';

export const seedRecipes: Recipe[] = [
  {
    id: uuidv4(),
    name: '番茄炒蛋',
    ingredients: [
      { name: '番茄', amount: 2, unit: '个', category: 'vegetable' },
      { name: '鸡蛋', amount: 3, unit: '个', category: 'other' },
      { name: '葱花', amount: 5, unit: '克', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散加少许盐' },
      { order: 2, description: '热油炒蛋，凝固后盛出' },
      { order: 3, description: '炒番茄出汁，加入鸡蛋翻炒' },
      { order: 4, description: '调味撒葱花出锅' },
    ],
    seasonings: [
      { name: '盐', amount: 3, unit: '克', category: 'seasoning' },
      { name: '白糖', amount: 5, unit: '克', category: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', category: 'seasoning' },
    ],
    cookTime: 15,
    difficulty: 'easy',
    cuisine: '家常菜',
    createdAt: Date.now() - 100000,
  },
  {
    id: uuidv4(),
    name: '红烧肉',
    ingredients: [
      { name: '五花肉', amount: 500, unit: '克', category: 'meat' },
      { name: '生姜', amount: 10, unit: '克', category: 'vegetable' },
      { name: '大葱', amount: 1, unit: '根', category: 'vegetable' },
      { name: '八角', amount: 2, unit: '颗', category: 'seasoning' },
    ],
    steps: [
      { order: 1, description: '五花肉切块焯水去血沫' },
      { order: 2, description: '炒糖色至枣红色' },
      { order: 3, description: '下肉块翻炒上色' },
      { order: 4, description: '加料酒酱油水，小火炖40分钟' },
      { order: 5, description: '大火收汁出锅' },
    ],
    seasonings: [
      { name: '生抽', amount: 20, unit: '毫升', category: 'seasoning' },
      { name: '老抽', amount: 10, unit: '毫升', category: 'seasoning' },
      { name: '料酒', amount: 30, unit: '毫升', category: 'seasoning' },
      { name: '冰糖', amount: 30, unit: '克', category: 'seasoning' },
    ],
    cookTime: 60,
    difficulty: 'medium',
    cuisine: '浙菜',
    createdAt: Date.now() - 200000,
  },
  {
    id: uuidv4(),
    name: '宫保鸡丁',
    ingredients: [
      { name: '鸡胸肉', amount: 300, unit: '克', category: 'meat' },
      { name: '花生米', amount: 50, unit: '克', category: 'grain' },
      { name: '干辣椒', amount: 10, unit: '个', category: 'vegetable' },
      { name: '黄瓜', amount: 1, unit: '根', category: 'vegetable' },
      { name: '葱白', amount: 20, unit: '克', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '鸡肉切丁腌制15分钟' },
      { order: 2, description: '调宫保汁备用' },
      { order: 3, description: '热油滑炒鸡丁变白盛出' },
      { order: 4, description: '爆香干辣椒花椒' },
      { order: 5, description: '回锅鸡丁加黄瓜花生米，淋汁翻炒' },
    ],
    seasonings: [
      { name: '花椒', amount: 2, unit: '克', category: 'seasoning' },
      { name: '生抽', amount: 15, unit: '毫升', category: 'seasoning' },
      { name: '醋', amount: 10, unit: '毫升', category: 'seasoning' },
      { name: '白糖', amount: 10, unit: '克', category: 'seasoning' },
      { name: '淀粉', amount: 5, unit: '克', category: 'seasoning' },
    ],
    cookTime: 25,
    difficulty: 'medium',
    cuisine: '川菜',
    createdAt: Date.now() - 300000,
  },
  {
    id: uuidv4(),
    name: '蒜蓉西兰花',
    ingredients: [
      { name: '西兰花', amount: 400, unit: '克', category: 'vegetable' },
      { name: '大蒜', amount: 5, unit: '瓣', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '西兰花切小朵盐水浸泡10分钟' },
      { order: 2, description: '焯水1分钟捞出过凉水' },
      { order: 3, description: '热油爆香蒜末' },
      { order: 4, description: '下西兰花快速翻炒调味' },
    ],
    seasonings: [
      { name: '盐', amount: 3, unit: '克', category: 'seasoning' },
      { name: '蚝油', amount: 10, unit: '克', category: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', category: 'seasoning' },
    ],
    cookTime: 10,
    difficulty: 'easy',
    cuisine: '素菜',
    createdAt: Date.now() - 400000,
  },
  {
    id: uuidv4(),
    name: '麻婆豆腐',
    ingredients: [
      { name: '嫩豆腐', amount: 400, unit: '克', category: 'other' },
      { name: '牛肉末', amount: 100, unit: '克', category: 'meat' },
      { name: '蒜苗', amount: 2, unit: '根', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '豆腐切块焯水去豆腥' },
      { order: 2, description: '炒牛肉末至酥香' },
      { order: 3, description: '加豆瓣酱炒出红油' },
      { order: 4, description: '加水烧开下豆腐烧3分钟' },
      { order: 5, description: '勾芡撒花椒粉蒜苗' },
    ],
    seasonings: [
      { name: '郫县豆瓣酱', amount: 20, unit: '克', category: 'seasoning' },
      { name: '花椒粉', amount: 3, unit: '克', category: 'seasoning' },
      { name: '生抽', amount: 10, unit: '毫升', category: 'seasoning' },
      { name: '淀粉', amount: 5, unit: '克', category: 'seasoning' },
    ],
    cookTime: 20,
    difficulty: 'easy',
    cuisine: '川菜',
    createdAt: Date.now() - 500000,
  },
  {
    id: uuidv4(),
    name: '土豆炖牛肉',
    ingredients: [
      { name: '牛腩', amount: 500, unit: '克', category: 'meat' },
      { name: '土豆', amount: 2, unit: '个', category: 'vegetable' },
      { name: '胡萝卜', amount: 1, unit: '根', category: 'vegetable' },
      { name: '洋葱', amount: 0.5, unit: '个', category: 'vegetable' },
      { name: '番茄', amount: 1, unit: '个', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '牛腩切块焯水洗净' },
      { order: 2, description: '爆香洋葱番茄出汁' },
      { order: 3, description: '加牛肉料酒香料水炖1小时' },
      { order: 4, description: '加土豆胡萝卜炖20分钟' },
      { order: 5, description: '大火收汁调味' },
    ],
    seasonings: [
      { name: '生抽', amount: 20, unit: '毫升', category: 'seasoning' },
      { name: '老抽', amount: 10, unit: '毫升', category: 'seasoning' },
      { name: '料酒', amount: 30, unit: '毫升', category: 'seasoning' },
      { name: '香叶', amount: 2, unit: '片', category: 'seasoning' },
      { name: '盐', amount: 5, unit: '克', category: 'seasoning' },
    ],
    cookTime: 90,
    difficulty: 'hard',
    cuisine: '家常菜',
    createdAt: Date.now() - 600000,
  },
  {
    id: uuidv4(),
    name: '鸡蛋羹',
    ingredients: [
      { name: '鸡蛋', amount: 2, unit: '个', category: 'other' },
      { name: '温水', amount: 150, unit: '毫升', category: 'other' },
      { name: '葱花', amount: 3, unit: '克', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '鸡蛋打散加温水过筛' },
      { order: 2, description: '盖保鲜膜扎小孔' },
      { order: 3, description: '水开后中火蒸8分钟' },
      { order: 4, description: '淋生抽香油撒葱花' },
    ],
    seasonings: [
      { name: '生抽', amount: 5, unit: '毫升', category: 'seasoning' },
      { name: '香油', amount: 3, unit: '毫升', category: 'seasoning' },
      { name: '盐', amount: 1, unit: '克', category: 'seasoning' },
    ],
    cookTime: 15,
    difficulty: 'easy',
    cuisine: '蒸菜',
    createdAt: Date.now() - 700000,
  },
  {
    id: uuidv4(),
    name: '鱼香肉丝',
    ingredients: [
      { name: '猪里脊', amount: 300, unit: '克', category: 'meat' },
      { name: '胡萝卜', amount: 0.5, unit: '根', category: 'vegetable' },
      { name: '青椒', amount: 1, unit: '个', category: 'vegetable' },
      { name: '木耳', amount: 30, unit: '克', category: 'vegetable' },
      { name: '泡椒', amount: 10, unit: '克', category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: '肉丝腌制上浆' },
      { order: 2, description: '调鱼香汁备用' },
      { order: 3, description: '滑炒肉丝变白盛出' },
      { order: 4, description: '炒香泡椒加蔬菜丝' },
      { order: 5, description: '回锅肉丝淋汁快速翻炒' },
    ],
    seasonings: [
      { name: '生抽', amount: 15, unit: '毫升', category: 'seasoning' },
      { name: '醋', amount: 15, unit: '毫升', category: 'seasoning' },
      { name: '白糖', amount: 15, unit: '克', category: 'seasoning' },
      { name: '淀粉', amount: 5, unit: '克', category: 'seasoning' },
    ],
    cookTime: 20,
    difficulty: 'medium',
    cuisine: '川菜',
    createdAt: Date.now() - 800000,
  },
];

export const seedFavorites: Favorite[] = [
  { recipeId: seedRecipes[0].id, order: 0, addedAt: Date.now() - 50000 },
  { recipeId: seedRecipes[1].id, order: 1, addedAt: Date.now() - 40000 },
  { recipeId: seedRecipes[3].id, order: 2, addedAt: Date.now() - 30000 },
];