import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import ReactDOM from 'react-dom/client';
import { runBatchChecks } from './batchScenarios';
import './batch.css';
const BatchPage = () => {
    const [report, setReport] = useState(() => runBatchChecks());
    return (_jsxs("div", { className: "batch-page", children: [_jsxs("header", { className: "batch-header", children: [_jsx("h1", { children: "\u82B1\u706F\u94FA \u00B7 \u591A\u4F5C\u54C1\u6279\u91CF\u81EA\u68C0" }), _jsxs("div", { className: "batch-actions", children: [_jsx("a", { className: "batch-btn ghost", href: "./index.html", children: "\u2190 \u8FD4\u56DE\u94FA\u9762" }), _jsx("button", { type: "button", className: "batch-btn", onClick: () => setReport(runBatchChecks()), children: "\u91CD\u65B0\u8FD0\u884C" })] })] }), _jsxs("div", { className: `summary ${report.passed ? 'ok' : 'fail'}`, children: [report.passed ? '✓ 全部通过' : '✗ 存在失败', " \u00B7", ' ', report.passedChecks, "/", report.totalChecks, " \u9879\u68C0\u67E5\u901A\u8FC7 \u00B7", ' ', report.scenarios.length, " \u4E2A\u573A\u666F"] }), report.scenarios.map((scenario) => (_jsxs("section", { className: "scenario", children: [_jsxs("h2", { className: scenario.passed ? 'ok' : 'fail', children: [scenario.passed ? '✓' : '✗', " ", scenario.title] }), _jsxs("ul", { className: "check-list", children: [scenario.checks.map((check, idx) => (_jsxs("li", { className: check.passed ? 'ok' : 'fail', children: [_jsx("span", { className: "mark", children: check.passed ? '✓' : '✗' }), _jsx("span", { className: "check-name", children: check.name }), check.detail && _jsx("span", { className: "detail", children: check.detail })] }, idx))), scenario.invariantViolations.map((v, idx) => (_jsxs("li", { className: "fail", children: [_jsx("span", { className: "mark", children: "\u2717" }), _jsx("span", { className: "check-name", children: "\u72B6\u6001\u4E0D\u53D8\u91CF\u88AB\u7834\u574F" }), _jsx("span", { className: "detail", children: v })] }, `v${idx}`)))] })] }, scenario.title)))] }));
};
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(BatchPage, {}) }));
