import type { Formation, FormationType } from './types';

export const FORMATIONS: Record<FormationType, Formation> = {
  yulin: {
    name: 'yulin',
    nameCN: '鱼鳞阵',
    description: '前锋尖锐，层层递进，适合突破',
    attackBonus: 1.3,
    defenseBonus: 0.9,
    positions: [
      { dx: 0, dy: -2, type: 'cavalry' },
      { dx: -1, dy: -1, type: 'cavalry' },
      { dx: 1, dy: -1, type: 'cavalry' },
      { dx: -2, dy: 0, type: 'infantry' },
      { dx: -1, dy: 0, type: 'infantry' },
      { dx: 0, dy: 0, type: 'infantry' },
      { dx: 1, dy: 0, type: 'infantry' },
      { dx: 2, dy: 0, type: 'infantry' },
      { dx: -2, dy: 1, type: 'archer' },
      { dx: -1, dy: 1, type: 'archer' },
      { dx: 0, dy: 1, type: 'infantry' },
      { dx: 1, dy: 1, type: 'archer' },
      { dx: 2, dy: 1, type: 'archer' },
      { dx: -1, dy: 2, type: 'infantry' },
      { dx: 1, dy: 2, type: 'infantry' },
    ],
  },
  fangyuan: {
    name: 'fangyuan',
    nameCN: '方圆阵',
    description: '阵型紧凑，防御稳固，适合坚守',
    attackBonus: 0.9,
    defenseBonus: 1.3,
    positions: [
      { dx: 0, dy: -2, type: 'infantry' },
      { dx: -1, dy: -2, type: 'archer' },
      { dx: 1, dy: -2, type: 'archer' },
      { dx: -2, dy: -1, type: 'infantry' },
      { dx: -1, dy: -1, type: 'cavalry' },
      { dx: 0, dy: -1, type: 'infantry' },
      { dx: 1, dy: -1, type: 'cavalry' },
      { dx: 2, dy: -1, type: 'infantry' },
      { dx: -2, dy: 0, type: 'archer' },
      { dx: -1, dy: 0, type: 'infantry' },
      { dx: 1, dy: 0, type: 'infantry' },
      { dx: 2, dy: 0, type: 'archer' },
      { dx: -1, dy: 1, type: 'cavalry' },
      { dx: 0, dy: 1, type: 'infantry' },
      { dx: 1, dy: 1, type: 'cavalry' },
    ],
  },
  heyi: {
    name: 'heyi',
    nameCN: '鹤翼阵',
    description: '两翼展开，包抄合围，适合围歼',
    attackBonus: 1.15,
    defenseBonus: 1.05,
    positions: [
      { dx: 0, dy: 0, type: 'infantry' },
      { dx: -1, dy: 0, type: 'infantry' },
      { dx: 1, dy: 0, type: 'infantry' },
      { dx: -2, dy: 0, type: 'cavalry' },
      { dx: 2, dy: 0, type: 'cavalry' },
      { dx: -3, dy: 1, type: 'archer' },
      { dx: -2, dy: 1, type: 'infantry' },
      { dx: 2, dy: 1, type: 'infantry' },
      { dx: 3, dy: 1, type: 'archer' },
      { dx: -3, dy: 2, type: 'cavalry' },
      { dx: -2, dy: 2, type: 'archer' },
      { dx: 2, dy: 2, type: 'archer' },
      { dx: 3, dy: 2, type: 'cavalry' },
      { dx: -1, dy: -1, type: 'infantry' },
      { dx: 1, dy: -1, type: 'infantry' },
    ],
  },
};
